//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McLaren_Store.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int CarID { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string EngineType { get; set; }
        public string Transmission { get; set; }
        public Nullable<bool> Available { get; set; }
        public byte[] Image { get; set; }
        public string Brand { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
