//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McLaren_Store.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerOrders
    {
        public int OrderID { get; set; }
        public int SaleID { get; set; }
        public int EmployeeID { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
